Improved reading of Mini Buoy data
Ale0430/MiniBuoy-App pull request #44
Opened 2023-08-21 09:54 UTC by cailadd90

- B4/B4+: users may select the wrong axes (x, z), so  this code takes the column names (including axis) from *CHANNEL column and assigns it to the *DATA column names. This is a more robust way to ensure the correct data is used for the analysis. A warning / error message may be needed if no Yacc data is provided.
- Pendant: reading data is simpler now, using the contains() function to look for the correct headers (date and x accel)
- Standardising datetime: The previous code wasn't working for Pendant data with 12 hour clock (PM data was being superimposed on AM data, leaving gaps where PM should be). Now, a nested if else statment looks for a date format (lubridate) and transforms into a standard yy-mm-dd hh-mm-ss if applicable. At the moment, mdy_hms() and ymd_hms() are being used, with the possibility of adding more options.
- Raw data was not being reported for the Skinflats Pendant test, had to add na.rm = T in the quanitle() function.

2023-08-25 08:02 UTC, mcwimm requested changes
B4 and B4+ test data are working, but not pendant clyde. Do you have an idea?

2023-08-25 08:11 UTC, cailadd90 commented
> 

Yes - try reducing the minimum tilt threshold to 50 and it should work? For some reason, this logger failed to be fully upright in the water column over the whole survey

2023-08-25 08:13 UTC, cailadd90 commented on R_scripts/functions/fun_data.R
> -   if (an.error.occured) {
> Why did you remove this? Without nomething happens if an error occured...

Ah OK - apologies, happy to retain?

2023-08-25 09:39 UTC, mcwimm commented
> > 
> 
> Yes - try reducing the minimum tilt threshold to 50 and it should work? For some reason, this logger failed to be fully upright in the water column over the whole survey

Ok. That worked. I included an `tryCatch` to throw an error messae. again, wording is only a placeholder...

2023-08-25 11:22 UTC, cailadd90 commented
That's really nice, thanks. Couple of points:

- It might be nice to have the error message appear under 'Table', e.g. "Unable to show table. Try refining the default settings" instead of a message - what do you think? Don't worry if it's complicated to amend.
- The error in the Current Velocity tab and the summary text could read "Unable to plot. Try refining the default settings" and "Unable to summarise. Try refining the default settings" respectively. Can these be amended?
- I also notice the error message appears twice for some reason

I've pushed a commit to reword the message slightly.

2023-08-25 13:01 UTC, mcwimm commented
Ahhh, I confused the error signals... now it should work.
Don't know why the pop up appears twice. we can add this on the list of issue with medium priority.

Please test again. There were several merge conflicts and I'm not 100% sure that I resolved them correctly.

2023-08-25 13:02 UTC, mcwimm approved these changes

2023-08-25 13:30 UTC, cailadd90 commented
Ah I did try:
1. git fetch --all
2. git checkout ReadingFiles
3. git rebase origin/ReadingFiles

But there are conflicts. I can see 3 instances of <<<<<<< HEAD in fun_data.R

2023-08-28 06:22 UTC, mcwimm commented
> Ah I did try:
> 
> 1. git fetch --all
> 2. git checkout ReadingFiles
> 3. git rebase origin/ReadingFiles
> 
> But there are conflicts. I can see 3 instances of <<<<<<< HEAD in fun_data.R

Yes, it's likely that there are conflicts, because I rebased the branch on the master... In this case you can reset your local branch to the only version (if you don't made any changes that are not yet included...)

2023-08-28 06:41 UTC, cailadd90 commented
I'll save my local branch just in case before I reset. “git reset --hard origin/ReadingFiles” right?

2023-08-28 06:42 UTC, mcwimm commented
> I'll save my local branch just in case before I reset. “git reset --hard origin/ReadingFiles” right?

Yes

2023-08-28 06:51 UTC, cailadd90 commented
Great - overwrote my local branch and tested. Successfully read examples files for B4, B4+ and Pendant. Happy for it to be merged :)

2023-08-28 06:59 UTC, merged